# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.srcs/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0.xci
# IP: The module: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.gen/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.gen/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.srcs/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0.xci
# IP: The module: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.gen/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.gen/sources_1/bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NEORV32_TopLevel_BD_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
