# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/doc/Arty_A7_100T.xdc

# Block Designs: bd/NEORV32_TopLevel_BD/NEORV32_TopLevel_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NEORV32_TopLevel_BD || ORIG_REF_NAME==NEORV32_TopLevel_BD} -quiet] -quiet

# IP: bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_neorv32_vivado_ip_0_0/NEORV32_TopLevel_BD_neorv32_vivado_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NEORV32_TopLevel_BD_neorv32_vivado_ip_0_0 || ORIG_REF_NAME==NEORV32_TopLevel_BD_neorv32_vivado_ip_0_0} -quiet] -quiet

# IP: bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_clk_wiz_0/NEORV32_TopLevel_BD_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NEORV32_TopLevel_BD_clk_wiz_0 || ORIG_REF_NAME==NEORV32_TopLevel_BD_clk_wiz_0} -quiet] -quiet

# IP: bd/NEORV32_TopLevel_BD/ip/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0/NEORV32_TopLevel_BD_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NEORV32_TopLevel_BD_rst_clk_wiz_100M_0 || ORIG_REF_NAME==NEORV32_TopLevel_BD_rst_clk_wiz_100M_0} -quiet] -quiet

# XDC: c:/Users/lapto/dev/fpga/arty-a7/projects/project_1/project_1.gen/sources_1/bd/NEORV32_TopLevel_BD/NEORV32_TopLevel_BD_ooc.xdc
